spring:
  #datasource:
    #url: jdbc:postgresql://localhost:5432/dev
    #username: dev
    #password: password
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/happy_events
    username: snegirev
    password: x3*vQUGz=b,>pB,#zN9_
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8081
  address: 0.0.0.0
logging:
  level:
    org:
      springframework:
        security: DEBUG